### ISSUE TITLE
rdf:type for inventors

### ISSUE THREAD

**Issue by luigiselmi** [fusepool/patents-reengineering#1]
The type (rdf:type) should be assigned to inventors. Currently only the name of the instance is available.

**Comment by csarven** [comment]
Currently there are no Inventor/Applicant/Assignee class but I've added sumo:CognitiveAgent, sumo:Human, foaf:Person, foaf:Organization for now.

Whether some thing is an inventor may be inferred from being an pmo:inventorOf . Not the best but okay. We could create special classes I guess. I will revisit this at a later date.

**Comment by retog** [comment]
Where can one get the rdf description of http://www.owl-ontologies.com/sumo.owl?

**Comment by csarven** [comment]
@retobg http://mklab.iti.gr/files/ontologies.rar contains sumo.owl. The SUMO URL is not dereferenceable, hence, we might a) leave it as is and just load sumo.owl into the store b) rewrite all references to SUMO to our own dereferenceable namespace.
