### ISSUE TITLE
Alignment Documentation and Queries

### ISSUE THREAD

**Issue by luigiselmi** [fusepool/patents-reengineering#11]
The XML->RDF alignment must be documented: 

1) Which ontologies have been used for the matching process and why. 
2) Logical level of the ontologies (DL, Full or other) and consistency 
3) Patterns used to create URIs for instances
4) Write some competency questions in natural language of interest for searching the patents to be translated in SPARQL queries.
5) Make a list of the entities that are mentioned in the documents and the properties that provide information about them (persons, organizations, ? )

**Comment by retog** [comment]
What about GRDDL?

**Comment by luigiselmi** [comment]
Developing an GRDDL aware enhancer will be a very good idea if our sources would provide a pointer to a transformation in their documents. The XML documents we are dealing with at the moment don't provide such pointers.

**Comment by csarven** [comment]
Added documentation to the wiki
