### ISSUE TITLE
Duplicate catalog files

### ISSUE THREAD

**Issue by csarven** [fusepool/patents-reengineering#15]
What's the purpose of:

https://github.com/fusepool/patents-reengineering/blob/master/catalog/catalog.xml and
https://github.com/fusepool/patents-reengineering/blob/master/src/main/resources/catalog/catalog.xml

when there is

https://github.com/fusepool/patents-reengineering/blob/master/lib/catalog.xml

**Comment by fifthoffour** [comment]
See: https://github.com/fusepool/patents-reengineering/issues/16

These will be deleted soon, however. In a new code version, dtd files will be managed  in a different way, so these folders will be unnecessary.
