### ISSUE TITLE
Remove XSLT and use Rdfizer instead

### ISSUE THREAD

**Issue by retog** [fusepool/patents-reengineering#26]
The stylesheets are now in fusepool-dlc-patents. As the dependecnies there are smaller than the Stanbol dependencies needed for the enhancer the XSLT should be there. The Enhancer should use an Rdfizer service for extracting the RDF.

**Comment by luigiselmi** [comment]
The enhancer uses a patent rdfizer service. The name of the service to use ("patent") is written in the code but it could be set in Felix config panel if needed. The xslt files are still in the project as some scripts for the xsl transformation could refer to them but are not used anymore for the transformation.

**Comment by retog** [comment]
As this project is about providing an enhancer the scripts are in the wrong place anyway. WDYT?
