### ISSUE TITLE
List of vocabs and other metadata to load into RDF store

### ISSUE THREAD

**Issue by csarven** [fusepool/patents-reengineering#9]
The following data should always reside in RDF store and be accessible from the default named graph.

patexpert
prov
dcterms
schema
filing-office

Basically all files under `meta/` directory if not listed above.

Also CPC schemes.

They should be loaded one file at a time instead of creating a single N-Triples in case the data contains bnodes.

**Comment by csarven** [comment]
Commit 37ef9cf5c9ab76bd54b86a5bdcf8f8a3f3edf4e9

**Comment by luigiselmi** [comment]
All the controlled vocabularies will be available as Stanbol ManagedSite.

**Comment by luigiselmi** [comment]
Or they could be available in the Ontology network
